MAX_XID = 0xffffffff

MCP_HEADER_PACK_STR = '!HIBI'
MCP_HEADER_SIZE = 11

# enum mcp_type
MCP_HELLO = 0
MCP_ERROR = 1
MCP_GET_CONFIG_REQUEST = 2
MCP_GET_CONFIG_REPLY = 3
MCP_SET_CONFIG = 4

MCP_JOB_CREATE_REQUEST = 5
MCP_JOB_CREATE_REPLY = 6
MCP_JOB_ACK = 7
MCP_JOB_STATE_CHANGE = 8

MCP_JOB_DELETE_REQUEST = 9
MCP_JOB_DELETE_REPLY = 10

MCP_JOB_RUNNING_OUTPUT = 11
MCP_JOB_DELETE_ALL = 12

MCP_JOB_OUTPUT = 13
MCP_JOB_FEATURE_EXE = 14

API_ACTION_EXCEPTION = 15
API_ACTION_LOGIN = 16
API_ACTION_LOGIN_RESPONSE = 17
API_ACTION_LOGIN_FAILED = 18

API_ACTION_REQUEST = 19
API_ACTION_RESPONSE = 20

CAPTURE_SERVICE_EXE = 21
CAPTURE_SERVICE_SEND_PKT = 22
CAPTURE_SERVICE_CANCEL_EXECUTE = 23
CAPTURE_SERVICE_SET_EVENT = 24
CAPTURE_SERVICE_SET_EXCEPTION = 25

CMD_SERVICE_EXE = 26
CMD_SERVICE_CANCEL_EXE = 27
CMD_SERVICE_READ_STD = 28
CMD_SERVICE_WRITE_STD = 29

CMD_SERVICE_READ_STD_RES = 30
CMD_SERVICE_WRITE_STD_RES = 31
CMD_SERVICE_READ_STD_EXCPTION = 32
CMD_SERVICE_WRITE_STD_EXCPTION = 33

CMD_SERVICE_SET_EVENT = 34
CMD_SERVICE_SET_EXCEPTION = 35

# mcp hello
MCP_HELLO_SIZE = 2
MCP_HELLO_STR = "!H"

MCP_JOB_ID_WITH_INFO_SIZE = 8
MCP_JOB_ID_WITH_INFO_STR = "!II"

# mcp job type
MCP_JOB_CREATE_REQUEST_SIZE = 8
MCP_JOB_CREATE_REQUEST_STR = "!II"

MCP_JOB_CREATE_REPLY_SIZE = 8
MCP_JOB_CREATE_REPLY_STR = "!II"

MCP_JOB_ACK_SIZE = 4
MCP_JOB_ACK_STR = "!I"

MCP_JOB_STATE_CHANGE_SIZE = 9
MCP_JOB_STATE_CHANGE_STR = "!IBI"

MCP_JOB_OUTPUT_SIZE = 9
MCP_JOB_OUTPUT_STR = "!IBI"

MCP_JOB_DELETE_REQUEST_SIZE = 4
MCP_JOB_DELETE_REQUEST_STR = "!I"

MCP_JOB_DELETE_REPLY_SIZE = 4
MCP_JOB_DELETE_REPLY_STR = "!I"

MCP_JOB_FEATURE_EXE_SIZE = 9
MCP_JOB_FEATURE_EXE_STR = "!IBI"

API_ACTION_EXCEPTION_SIZE = 4
API_ACTION_EXCEPTION_STR = "!I"

API_ACTION_LOGIN_SIZE = 6
API_ACTION_LOGIN_STR = "!HI"

API_ACTION_LOGIN_RESPONSE_SIZE = 6
API_ACTION_LOGIN_RESPONSE_STR = "!HI"

API_ACTION_LOGIN_FAILED_SIZE = 2
API_ACTION_LOGIN_FAILED_STR = "!H"

API_ACTION_REQUEST_SIZE = 7
API_ACTION_REQUEST_STR = "!BHI"

API_ACTION_RESPONSE_SIZE = 4
API_ACTION_RESPONSE_STR = "!I"

CAPTURE_SERVICE_EXE_SIZE = 7
CAPTURE_SERVICE_EXE_STR = "!HBI"

CAPTURE_SERVICE_SEND_PKT_SIZE = 6
CAPTURE_SERVICE_SEND_PKT_STR = "!HI"

CAPTURE_SERVICE_CANCEL_EXECUTE_SIZE = 2
CAPTURE_SERVICE_CANCEL_EXECUTE_STR = "!H"

CAPTURE_SERVICE_SET_EVENT_SIZE = 3
CAPTURE_SERVICE_SET_EVENT_STR = "!HB"

CAPTURE_SERVICE_SET_EXCEPTION_SIZE = 6
CAPTURE_SERVICE_SET_EXCEPTION_STR = "!HI"

CMD_SERVICE_EXE_SIZE = 6
CMD_SERVICE_EXE_STR = "!HI"

CMD_SERVICE_CANCEL_EXECUTE_SIZE = 2
CMD_SERVICE_CANCEL_EXECUTE_STR = "!H"

CMD_SERVICE_READ_STD_SIZE = 7
CMD_SERVICE_READ_STD_STR = "!HBI"

CMD_SERVICE_WRITE_STD_SIZE = 6
CMD_SERVICE_WRITE_STD_STR = "!HI"

CMD_SERVICE_READ_STD_RES_SIZE = 6
CMD_SERVICE_READ_STD_RES_STR = "!HI"

# CMD_SERVICE_WRITE_STD_RES_SIZE = 6
# CMD_SERVICE_WRITE_STD_RES_STR = "!HI"

CMD_SERVICE_READ_STD_EXCEPTION_SIZE = 6
CMD_SERVICE_READ_STD_EXCEPTION_STR = "!HI"

CMD_SERVICE_WRITE_STD_EXCEPTION_SIZE = 6
CMD_SERVICE_WRITE_STD_EXCEPTION_STR = "!HI"

CMD_SERVICE_SET_EVENT_SIZE = 3
CMD_SERVICE_SET_EVENT_STR = "!HB"

CMD_SERVICE_SET_EXCEPTION_SIZE = 6
CMD_SERVICE_SET_EXCEPTION_STR = "!HI"