MAX_XID = 0xffffffff

MCP_HEADER_PACK_STR = '!HIBI'
MCP_HEADER_SIZE = 11

# enum mcp_type
MCP_HELLO = 0
MCP_ERROR = 1
MCP_GET_CONFIG_REQUEST = 2
MCP_GET_CONFIG_REPLY = 3
MCP_SET_CONFIG = 4

MCP_JOB_CREATE_REQUEST = 5
MCP_JOB_CREATE_REPLY = 6
MCP_JOB_ACK = 7
MCP_JOB_STATE_CHANGE = 8

MCP_JOB_DELETE_REQUEST = 9
MCP_JOB_DELETE_REPLY = 10

MCP_JOB_RUNNING_OUTPUT = 11
MCP_JOB_DELETE_ALL = 12

MCP_JOB_OUTPUT = 13
MCP_JOB_FEATURE_EXE = 14

API_ACTION_EXCEPTION = 15
API_ACTION_LOGIN = 16
API_ACTION_LOGIN_RESPONSE = 17
API_ACTION_LOGIN_EXCEPTION = 20

API_ACTION_REQUEST = 18
API_ACTION_RESPONSE = 19

# mcp hello
MCP_HELLO_SIZE = 2
MCP_HELLO_STR = "!H"

MCP_JOB_ID_WITH_INFO_SIZE = 8
MCP_JOB_ID_WITH_INFO_STR = "!II"

# mcp job type
MCP_JOB_CREATE_REQUEST_SIZE = 8
MCP_JOB_CREATE_REQUEST_STR = "!II"

MCP_JOB_CREATE_REPLY_SIZE = 8
MCP_JOB_CREATE_REPLY_STR = "!II"

MCP_JOB_ACK_SIZE = 4
MCP_JOB_ACK_STR = "!I"

MCP_JOB_STATE_CHANGE_SIZE = 9
MCP_JOB_STATE_CHANGE_STR = "!IBI"

MCP_JOB_OUTPUT_SIZE = 9
MCP_JOB_OUTPUT_STR = "!IBI"

MCP_JOB_DELETE_REQUEST_SIZE = 4
MCP_JOB_DELETE_REQUEST_STR = "!I"

MCP_JOB_DELETE_REPLY_SIZE = 4
MCP_JOB_DELETE_REPLY_STR = "!I"

MCP_JOB_FEATURE_EXE_SIZE = 9
MCP_JOB_FEATURE_EXE_STR = "!IBI"

API_ACTION_EXCEPTION_SIZE = 4
API_ACTION_EXCEPTION_STR = "!I"

API_ACTION_LOGIN_SIZE = 4
API_ACTION_LOGIN_STR = "!I"

API_ACTION_LOGIN_RESPONSE_SIZE = 4
API_ACTION_LOGIN_RESPONSE_STR = "!I"

API_ACTION_REQUEST_SIZE = 5
API_ACTION_REQUEST_STR = "!BI"

API_ACTION_RESPONSE_SIZE = 4
API_ACTION_RESPONSE_STR = "!I"