API_ACTION_CONTROLLER_MASTER_APP_NAME = 'api_action_master_handler'
API_ACTION_CONTROLLER_AGENT_APP_NAME = 'api_action_agent_handler'
DEFAULT_LOGIN_TIMEOUT = 5
DEFAULT_SESSION_INIT_TIMEOUT = 5
REMOTE_REQUEST_DEFAULT_TIMEOUT = 300 # 5 mins
AGENT_LOCAL = 'local'
