MAX_XID = 0xffffffff

MCP_HEADER_PACK_STR = '!HII'
MCP_HEADER_SIZE = 10

# enum mcp_type
MCP_HELLO = 0
MCP_ERROR = 1
MCP_GET_CONFIG_REQUEST = 2
MCP_GET_CONFIG_REPLY = 3
MCP_SET_CONFIG = 4

MCP_JOB_CREATE_REQUEST = 5
MCP_JOB_CREATE_REPLY = 6
MCP_JOB_ACK = 7
MCP_JOB_STATE_INFORM = 8

MCP_JOB_DELETE_REQUEST = 9
MCP_JOB_DELETE_REPLY = 10

# mcp hello
MCP_HELLO_SIZE = 2
MCP_HELLO_STR = "!H"

# mcp job type
MCP_JOB_CREATE_REQUEST_SIZE = 8
MCP_JOB_CREATE_REQUEST_STR = "!II"

MCP_JOB_CREATE_REPLY_SIZE = 8
MCP_JOB_CREATE_REPLY_STR = "!II"

MCP_JOB_ACK_SIZE = 4
MCP_JOB_ACK_STR = "!I"

MCP_JOB_STATE_INFORM_SIZE = 0
MCP_JOB_STATE_INFORM_STR = ""

MCP_JOB_DELETE_REQUEST_SIZE = 4
MCP_JOB_DELETE_REQUEST_STR = "!I"

MCP_JOB_DELETE_REPLY_SIZE = 4
MCP_JOB_DELETE_REPLY_STR = "!I"
